name: sync-panther-analysis-from-upstream

on:
  schedule:
    # 15:00Z every Wednesday
    - cron: "00 15 * * 3"
  workflow_dispatch: # or on button click

env:
  YOUR_REPO_PRIMARY_BRANCH_NAME: "master"
  YOUR_REPO_NAME: "ben-githubs/monorepo"
  PATH_TO_PA: "panther_analysis"

jobs:
  check_upstream:
    if: | 
      github.repository != 'panther-labs/panther-analysis'
    runs-on: ubuntu-latest
    steps:
      ## CRAETE LOCAL REPO
      - name: Create Local Repo
        uses: actions/checkout@v4
      ## CHECK LATEST RELEASE
      - id: get_tag
        name: Get Latest Release
        run: |
          LATEST_TAG=$(git -c 'versionsort.suffix=-' \
            ls-remote --exit-code --refs --sort='version:refname' --tags https://github.com/panther-labs/panther-analysis.git '*.*.*' \
            | tail --lines=1 \
            | cut -d '/' -f 3)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      ## CREATE NEW BRANCH
      - id: create_branch
        name: Create New Branch
        run: |
          BRANCH_NAME="panther_analysis_sync_${{ steps.get_tag.outputs.tag }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git checkout -b $BRANCH_NAME
          git subtree pull --prefix {{ env.PATH_TO_PA }} https://github.com/panther-labs/panther-analysis.git ${{ steps.get_tag.outputs.tag }} --squash -m "Updating Panther Analysis to version ${{ steps.get_tag.outputs.tag }}"
      ## CHECK FOR UPDATES
      - id: check_updates
        name: Check for Updates
        run: |
          [[ ! -z $(git status --porcelain) ]] && HAS_CHANGES="yes" || HAS_CHANGES="no"
          echo "has_changes=$HAS_CHANGES ">> $GITHUB_OUTPUT
      ## PUSH AND MAKE PR
      - id: create_pr
        name: Push and Create PR
        if: ${{ steps.check_updates.outputs.has_changes == 'yes' }}
        run: |
          git commit -m "Updating Panther Analysis to version $LATEST_TAG"
          git push --set-upstream origin panther_analysis_sync_v3.31.0
          gh pr create --title "Update Panther Analysis to $LATEST_TAG" --fill --base $YOUR_MAIN_BRANCH --repo $YOUR_REPO
