name: upload-to-panther

on:
    push:
      branches:
        - main
    workflow_dispatch:
  
jobs:
  upload:
    name: 
    runs-on: ubuntu-latest
    env:
      API_HOST: ${{ secrets.PANTHER_API_HOST }}
      API_TOKEN: ${{ secrets.PANTHER_API_TOKEN }}
    steps:
      - name: Validate Secrets
        if: ${{ env.API_HOST == '' || env.API_TOKEN == '' }}
        run: |
          echo "API_HOST or API_TOKEN not set"
          exit 0

      - name: Checkout panther-analysis
        uses: actions/checkout@v4

      - name: Set python version  
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install pipenv
        working-directory: ./panther_analysis
        run: pip install pipenv
      
      - name: Install
        working-directory: ./panther_analysis
        run: make install
      
      - name: Setup venv
        working-directory: ./panther_analysis
        run: make venv

      - name: upload
        working-directory: ./panther_analysis
        run: |
            pipenv run panther_analysis_tool upload --api-host ${{ env.API_HOST }} --api-token ${{ env.API_TOKEN }}